module.exports = [
  'Beehive Meadows',
  'Bridalveil Campground',
  'Budd Creek (cross-country only)',
  'Cathedral Lakes',
  'Chilnualna Falls',
  'Deer Camp',
  'Gaylor Lakes (no camping)',
  'Glacier Point->Illilouette',
  'Glacier Point->Illilouette',
  'Glacier Point->Little Yosemite Valley',
  'Glen Aulin',
  'Glen Aulin->Cold Canyon/Waterwheel (pass through)',
  'Happy Isles->Illilouette',
  'Happy Isles->Little Yosemite Valley',
  'Happy Isles->Sunrise/Merced Lake (pass through)',
  'Luken->Lukens Lake',
  'Lukens Lake->Yosemite Creek',
  'Lyell Canyon',
  'Mather Ranger Station',
  'May Lake',
  'May Lake->Snow Creek',
  'McGurk  Meadow', // FIXME: Account for double spaces between trailhead names
  'Mirror Lake->Snow Creek',
  'Mono Meadow',
  'Mono/Parker Pass',
  'Murphy Creek',
  'Nelson  Lake',
  'Old Big Oak Flat Road',
  'Olmsted Point',
  'Ostrander (Lost Bear Meadow)',
  'Pohono Trail (Glacier Point)',
  'Pohono Trail (Taft Point)',
  'Pohono Trail (Wawona Tunnel/Bridalveil Parking)',
  'Porcupine Creek',
  'Rafferty Creek->Vogelsang',
  'Rancheria Falls',
  'Rockslides',
  'Sunrise Lakes',
  'Tamarack Creek',
  'Ten Lakes',
  'White Wolf Campground',
  'White Wolf->Pate Valley',
  'White Wolf->Pate Valley',
  'Yosemite Creek Campground',
  'Yosemite Falls',
  'Young Lakes via Dog Lake',
  'Young Lakes via Glen Aulin Trail'
];